create table TB_ADDRESS (
	SEQ		INT	PRIMARY KEY AUTO_INCREMENT
	, FIRST_NAME	VARCHAR(32)
	, LAST_NAME		VARCHAR(32)
	, PHONE			VARCHAR(32)
) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

INSERT INTO TB_ADDRESS VALUES (0, '수현', '배', '123456789');
INSERT INTO TB_ADDRESS VALUES (0, '길동', '홍', '123456789');
INSERT INTO TB_ADDRESS VALUES (0, '현규', '강', '123456789');